Code restructure
healhealth/website pull request #12
Opened 2023-05-15 18:05 UTC by DEJENERUTA

2023-05-18 08:02 UTC, bence-toth requested changes
Can you please summarise the changes in the PR description? Especially when you have 33 files in a PR changed, it would be easier to get an overview of the changes.

2023-05-18 08:02 UTC, bence-toth commented on src/App.tsx
> +import Header from "./components/Header";
Why is this only component in the `src` folder while all the rest are in `src/components`?

2023-05-18 08:02 UTC, bence-toth commented on src/components/Join.tsx
> +    <section className="join">
What is the point of this class `join`? I don't see it used anywhere.

2023-05-18 08:02 UTC, bence-toth commented on src/components/OurCoreValue.tsx
> +        new members to join our team on a voluntary or unpaid internship basis.
I'd probably ditch `We are excited to announce that` from the text.

2023-05-18 08:02 UTC, bence-toth commented on src/components/OurCoreValue.tsx
> +        in touch with us at the email address: nashmil@healhealth.dk. We look
This should be a clearer call to action:
1) The email should be wrapped in an `<a>` tag with a `mailto:` value on the `href` attribute pointing to the email address.
2) I recommend adding the same link styled as a button to the end of the section (after the last paragraph), pointing to the same email address, with a text like `Join us today`.

2023-05-18 08:02 UTC, bence-toth commented on src/components/OurCoreValue.css
> +.site-main-inner-wrapper-core {
This class breaks the existing structure of the sections, and therefore will make it more difficult to make the website responsive.

I recommend using the `.site-main-inner-wrapper` class name in `OurCoreValue.tsx` as in other sections, and just ditching this CSS file entirely.

2023-05-18 08:16 UTC, bence-toth requested changes

2023-05-18 08:16 UTC, bence-toth commented on src/components/OurCoreValue.tsx
> +        backgrounds and experiences. If you're interested in joining our team
Pay attention to using the typographically correct apostrophes in text.

Instead of `'`, use `’`, it will make the text look so much nicer!

2023-05-20 10:14 UTC, DEJENERUTA commented on src/components/OurCoreValue.tsx
> +        new members to join our team on a voluntary or unpaid internship basis.
I am waiting the real our core value text from Nashmil, the one I used is, I just copy from join us component

2023-05-24 09:19 UTC, Poorooshka reviewed
Please correct the followings:
1- In line 4 the title 'Our Core Value' should be replaced by 'Our Core Values' as we have more than 1 value.

2- In line 19 'utual Respect' is wrong and should be 'Mutual Respect'

2023-05-24 09:24 UTC, Poorooshka commented on src/images/dejene.png
please take a new picture that looks like the other members with better quality and resize it to 400 × 400 pixels and save it as jpg

2023-05-24 09:26 UTC, Poorooshka commented on src/components/OurCoreValue.tsx
line 4, 'Our Core Values' is correct as it should be plural.

line 19, 'Mutual Respect' is the correct word.

2023-05-24 10:20 UTC, Poorooshka commented on src/components/Join.tsx
line 24, please change the email address to info@healhealth.dk

2023-05-24 10:25 UTC, Poorooshka commented on src/components/Services.tsx
line 28 and line 30, the word 'well-being' should be corrected into 'wellbeing'

2023-05-24 20:01 UTC, bence-toth requested changes
I just fixed most of @Poorooshka's comments as well as some other style and markup issues and the linter error. There's still a few conversations open that have to be addressed.

2023-05-25 16:53 UTC, bence-toth approved these changes

2023-05-26 06:50 UTC, merged